# Configuration file for TrackDrop
# This file contains default values for local development
# In Docker, this file is generated by entrypoint.sh from environment variables

import os

# Navidrome Configuration
ROOT_ND = ""
USER_ND = ""
PASSWORD_ND = ""
MUSIC_LIBRARY_PATH = "/path/to/music"
TEMP_DOWNLOAD_FOLDER = "/path/to/temp"

# ListenBrainz API Configuration
LISTENBRAINZ_ENABLED = False
ROOT_LB = "https://api.listenbrainz.org"
TOKEN_LB = ""
USER_LB = ""

# Last.fm API Configuration
LASTFM_ENABLED = False
LASTFM_API_KEY = ""
LASTFM_API_SECRET = ""
LASTFM_USERNAME = ""
LASTFM_PASSWORD = ""
LASTFM_PASSWORD_HASH = ""
LASTFM_SESSION_KEY = ""

# LLM Suggestions Settings
LLM_ENABLED = False
LLM_PROVIDER = ""
LLM_API_KEY = ""
LLM_MODEL_NAME = ""
LLM_BASE_URL = ""

# Spotify API Configuration (for playlist extraction - Client Credentials flow)
SPOTIFY_CLIENT_ID = ""
SPOTIFY_CLIENT_SECRET = ""

# Deezer Configuration
DEEZER_ARL = ""

# Download Method
DOWNLOAD_METHOD = "streamrip"

# Album Recommendation Settings
ALBUM_RECOMMENDATION_ENABLED = os.getenv('ALBUM_RECOMMENDATION_ENABLED', 'false').lower() == 'true'

# UI Visibility Settings
HIDE_DOWNLOAD_FROM_LINK = os.getenv('HIDE_DOWNLOAD_FROM_LINK', 'false').lower() == 'true'
HIDE_FRESH_RELEASES = os.getenv('HIDE_FRESH_RELEASES', 'false').lower() == 'true'

# Download History JSON path (tracks downloaded files for cleanup)
DOWNLOAD_HISTORY_PATH = "/app/data/download_history.json"

# Admin credentials for library scan (startScan requires admin privileges)
ADMIN_USER = ""
ADMIN_PASSWORD = ""

# Path to Navidrome's database (read-only, for checking ratings across all users)
NAVIDROME_DB_PATH = ""

# Caching for fresh releases (in seconds)
FRESH_RELEASES_CACHE_DURATION = 300

# Deezer API Rate Limiting
DEEZER_MAX_CONCURRENT_REQUESTS = 3
